---
services:
  sql:
    container_name: mar-mar
    image: mariadb:10.5
    restart: unless-stopped
    env_file: .env
    environment:
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - persist-data:/var/lib/mysql
      - ./queries:/root/
    cap_add:
      - all

volumes:
  persist-data:
---
services:
  nosql:
    container_name: mon-mon
    image: mongo
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - persist-mongo:/data/db
volumes:
  persist-mongo:
