apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-dregistry   # Name of the Deployment
  namespace: wordpress       # The namespace in which this Deployment resides
  labels:
    app: wordpress           # Labels to identify the application
spec:
  replicas: 1                # Number of desired replicas
  selector:
    matchLabels:
      app: wordpress          # Select pods with these labels
      tier: docker-registry
  strategy:
    type: Recreate           # The update strategy for pods
  template:
    metadata:
      labels:
        app: wordpress        # Labels for the pod template
        tier: docker-registry
    spec:
      containers:
        - name: wordpress-dregistry
          image: registry     # Docker image to use for the container
          ports:
            - containerPort: 5000  # Port to expose on the container
          volumeMounts:
            - name: wordpress-registry
              mountPath: /var/lib/registry  # Mount the volume at this path in the container
      volumes:
        - name: wordpress-registry
          persistentVolumeClaim:
            claimName: dregistry-pv-claim  # Claim the persistent volume for this volume

