# Persistent Volume Claim for WordPress
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: wp-pv-claim            # Name of the PVC
  labels:
    app: wordpress             # Labels to identify the application
spec:
  accessModes:
    - ReadWriteOnce            # Access mode for the volume
  resources:
    requests:
      storage: 10Gi            # Requested storage size
  storageClassName: wordpress-storage-class   # Storage class name

# Persistent Volume Claim for MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: mysql-pv-claim         # Name of the PVC
  labels:
    app: wordpress             # Labels to identify the application
spec:
  accessModes:
    - ReadWriteOnce            # Access mode for the volume
  resources:
    requests:
      storage: 10Gi            # Requested storage size
  storageClassName: mysql-storage-class   # Storage class name

# Persistent Volume Claim for Docker Registry
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: dregistry-pv-claim     # Name of the PVC
  labels:
    app: wordpress             # Labels to identify the application
spec:
  accessModes:
    - ReadWriteOnce            # Access mode for the volume
  resources:
    requests:
      storage: 10Gi            # Requested storage size
  storageClassName: dregistry-storage-class  # Storage class name

