---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: wp-pv            
spec:
  capacity:
    storage: 10Gi        
  accessModes:
    - ReadWriteMany      
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wp-sc
  hostPath:
    path: /var/data/wordpress

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: mysql-pv               
spec:
  capacity:
    storage: 10Gi              
  accessModes:
    - ReadWriteMany            
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: mysql-sc
  hostPath:
    path: /var/data/mysql
