---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: wordpress-pv           
spec:
  capacity:
    storage: 10Gi              
  accessModes:
    - ReadWriteOnce            
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: wordpress-storage-class 
  hostPath:
    path: /var/data/wordpress  

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: mysql-pv               
spec:
  capacity:
    storage: 10Gi              
  accessModes:
    - ReadWriteOnce            
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: mysql-storage-class 
  hostPath:
    path: /var/data/mysql    

      #apiVersion: v1
      #kind: PersistentVolume
      #metadata:
      #  namespace: wordpress
      #  name: dregistry-pv            # Name of the PV
      #spec:
      #  capacity:
      #    storage: 10Gi               # Capacity of the volume
      #  accessModes:
      #    - ReadWriteOnce             # Access mode for the volume
      #  persistentVolumeReclaimPolicy: Retain  # Reclaim policy for the volume
      #  storageClassName: dregistry-storage-class  # Storage class name
      #  hostPath:
      #    path: /var/data/dregistry    # Host path where the volume is located
      #
