---
apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: wp-exposer
  labels:
    app: wordpress             
spec:
  type: NodePort               
  ports:
    - port: 80                 
      targetPort: 80           
  selector:
    app: wordpress             
    tier: frontend             
---
apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: wp-sql-bridge
  labels:
    app: wordpress             
spec:
  ports:
    - port: 3306               
      targetPort: 3306
  selector:
    app: wordpress             
    tier: mysql                
  clusterIP: None              
