---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: wordpress
  name: wp-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer  

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: wordpress
  name: mysql-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer  
