---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: wordpress
  name: wordpress-storage-class    
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer  

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: wordpress
  name: mysql-storage-class         
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer  

  #apiVersion: storage.k8s.io/v1
  #kind: StorageClass
  #metadata:
  #  namespace: wordpress
  #  name: dregistry-storage-class      # Name of the StorageClass
  #provisioner: kubernetes.io/no-provisioner   # The provisioner for the StorageClass
  #volumeBindingMode: WaitForFirstConsumer    # Volume binding mode
  #
