# Deployment for WordPress
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress
  name: wordpress               # Name of the Deployment
  labels:
    app: wordpress             # Labels to identify the application
spec:
  replicas: 1                  # Number of desired replicas
  selector:
    matchLabels:
      app: wordpress            # Select pods with these labels
      tier: frontend
  strategy:
    type: Recreate             # The update strategy for pods
  template:
    metadata:
      labels:
        app: wordpress          # Labels for the pod template
        tier: frontend
    spec:
      containers:
        - image: wordpress       # Docker image to use for the container
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql  # Database host for WordPress
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-mysql-secret  # Reference to the secret for DB password
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_USER
              value: wordpress         # WordPress DB user
            - name: WORDPRESS_DB_NAME
              value: wordpress         # WordPress DB name
          ports:
            - containerPort: 80        # Port to expose for WordPress
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html    # Mount path for WordPress data
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim        # Claim the persistent volume for WordPress

