version: '3.9'
services:

  web1:
    image: nginx
    container_name: web1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./index/index1.html:/usr/share/nginx/html/index.html
    ports:
      - "8081:80"
    environment:
      - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    networks:
      - default
      

  web2:
    image: nginx
    container_name: web2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./index/index2.html:/usr/share/nginx/html/index.html
    ports:
      - "8082:80"
    environment:
      - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    networks:
      - default
      

  web3:
    image: nginx
    container_name: web3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./index/index3.html:/usr/share/nginx/html/index.html
    ports:
      - "8083:80"
    environment:
      - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    networks:
        - default

networks:
  default:
    name: haproxy
