apiVersion: v1
kind: ConfigMap
metadata:
  name: dregistry-config
  namespace: wordpress
data:
  config.yml: |
    version: 0.1
    log:
      accesslog:
        disabled: true
      level: debug
      formatter: text
      fields:
        service: registry
        environment: staging
    auth:
      token:
        autoredirect: true
        realm: http://10.110.0.2/auth
        service: wordpress-dregistry
        issuer: wordpress-dregistry
