apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mysql-secret  # Name of the Secret
  namespace: wordpress        # The namespace in which this Secret resides
type: Opaque                  # Type of the secret (Opaque means arbitrary data)
data:
  MYSQL_ROOT_PASSWORD: d2lu   # Encoded data: MYSQL_ROOT_PASSWORD = "d2lu"
  MYSQL_PASSWORD: d2lu        # Encoded data: MYSQL_PASSWORD = "d2lu"
  WORDPRESS_DB_PASSWORD: d2lu  # Encoded data: WORDPRESS_DB_PASSWORD = "d2lu"
